### ISSUE TITLE
footnote内にhrefを書けるようにしてほしい

### ISSUE THREAD

**Issue by muojp** [vvakame/language-review#28]
mstsskが嘆いていたのでメモ。

要素内のネスト構造自体をサポートしてない??

**Comment by vvakame** [comment]
あれ？できなかったっけそれ？？

**Comment by vvakame** [comment]
あー…できないわ… arg部分がプレーンテキストなのか引数なのかreview構文なのか一意じゃないんだよね…

**Comment by vvakame** [comment]
https://github.com/vvakame/review.js/issues/17 で引き取る。
