### ISSUE TITLE
文章書いてプレビューのリロードが行われた後、プレビューのスクロールの位置をリロード前の場所に戻したい

### ISSUE THREAD

**Issue by anchan828** [vvakame/language-review#34]
毎回スクロールするの疲れました...!!

**Comment by vvakame** [comment]
わかる…プレビューの話だよね？
patches welcome!

あまり簡単じゃない解決策としてはreview.jsでDOMBuilderを追加してDOM要素に何行目か埋め込んで毎回そこにjumpするという…。
雑な解決策としてはreload前にsctollTop保存しといて復元するという。

**Comment by anchan828** [comment]
あ、そうですプレビューの話です。

Mou みたいな追従機能（エディット側をスクロールするとプレビュー側も追従する）はいらない気がするので雑な解決策で困らないんじゃないかなーと。

**Comment by vvakame** [comment]
雑な解決で対応した。
