### ISSUE TITLE
特定の .re ファイルのプレビューが見られない

### ISSUE THREAD

**Issue by kubosho** [vvakame/language-review#35]
![2015-11-01 01 59 39](https://cloud.githubusercontent.com/assets/430267/10864798/5582d040-803c-11e5-9754-b9b2d757c3a5.png)

- 開けない Re:VIEW ファイル: https://gist.github.com/kubosho/0cd2598fb19bed160626
  - .re ファイル内にある画像自体は https://github.com/o2project/start-dash-of-site-making/tree/master/images 配下にあります

---

OS: OS X El Capitan 10.11.1

(*'-') < apm -v
apm  1.1.1
npm  2.13.3
node 0.10.40
python 2.7.9
git 2.2.1

**Comment by vvakame** [comment]
https://github.com/vvakame/language-review/commit/89e7edaffff08e9333dc395aafa156729a568f67
コンパイル失敗時もプレビューを更新するようにしますた。もう一回試してみてください。
https://github.com/vvakame/language-review/issues/31 が行われるとよりわかりやすくなるはず…。

**Comment by vvakame** [comment]
ぱっと見た感じ、TOP などの見出しがダブってるので =={hoge-TOP} TOP みたいなラベル名を別途定義してやると乗りきれるはず…

**Comment by vvakame** [comment]
なお、画像は `ch01_01.jpg` より `ch01/01.jpg` としたほうがよいです。
https://github.com/kmuto/review/wiki/ImagePath

**Comment by kubosho** [comment]
> TOP などの見出しがダブってるので =={hoge-TOP} TOP みたいなラベル名を別途定義してやると乗りきれるはず…
まさにこれでした。この対応をしてみます。

**Comment by kubosho** [comment]
> なお、画像は ch01_01.jpg より ch01/01.jpg としたほうがよいです。

ありがとうございます！

**Comment by kubosho** [comment]
@vvakame 

プレビューが見られるようになりました。デバッグログの出力対応と、失敗時のプレビューの更新対応ありがとうございます！
