### ISSUE TITLE
//list等のコードブロックでlangを指定したときにエラーが出る

### ISSUE THREAD

**Issue by takahashim** [vvakame/language-review#38]
Re:VIEWのv1.5.0から、`//list`などのブロックが、

```review
//list[mrb_string_p][mrb_string_p(include/mruby/value.h)][c]{
#define mrb_string_p(o) (mrb_type(o) == MRB_TT_STRING)
//}
```

のように、最後の引数としてlangを指定できるようになりました (cf. https://github.com/kmuto/review/commit/5b9c754b1c10a559e97757940d3ec181b92e52eb )
ところがlanguage-reviewはこれに対応していないようで、langを指定するとpreviewが一切表示されず悲しい感じになります…。

**Comment by vvakame** [comment]
対応しました！

**Comment by takahashim** [comment]
@vvakame  う、すみません、わかりにくかったかも知れませんが、`//listnum`と`//emlistnum`も対応していただければ…ッ

**Comment by takahashim** [comment]
あ、違った、再起動したらちゃんと読めました！　どうもでした！
