### ISSUE TITLE
Re:VIEWのコメント行(#@...)はプレビューから消したい

### ISSUE THREAD

**Issue by takahashim** [vvakame/language-review#39]
下記のように、Re:VIEWの`#@mapfile()` 〜 `#@end`を使って、review-preprocでソースを同期させることがあります。

```c
//listnum[hello][hello.c][c]{
#@mapfile(../src/hello/hello.c)
#include <mruby.h>
#include <mruby/compile.h>

int
main(void)
{
  mrb_value result;
  mrb_state *mrb = mrb_open();
  result = mrb_load_string(mrb, "p 'hello world!'");
  mrb_close(mrb);
  return 0;
}
#@end
//}
```

で、現状ではプレビュー画面にも`#@mapfile...`の行が出力されてしまいます。これは最終的な版面には表示されないものなので、プレビューからも消去してもらえるとありがたいです。

（基本は`#@`で始まる行はコメントなので全部消してしまってOKです）

**Comment by vvakame** [comment]
対応しました。
ブロック記法内部で全ての文法を許したりインライン記法だけを許したり全部許さなかったりというパターンがあると認識していて、綺麗に対応するのが難しいので頑張って対応しました。
v0.11.10 で修正。

**Comment by takahashim** [comment]
ありがとうございます！！
