### ISSUE TITLE
この記事→この記ことに直せとwarningが表示される

### ISSUE THREAD

**Issue by tomorrowkey** [vvakame/language-review#40]
`この記事`って書くと`'こと'漢字で書かず、ひらがなで書くと読みやすくなります`とワーニングが表示される

**Comment by tomorrowkey** [comment]
たぶんこのへん https://github.com/vvakame/language-review/blob/2e83d74feb38295254d4ccdbf01b508f6f5c6485/example/prh.yml#L65-L67

**Comment by vvakame** [comment]
prh内のtechbooster.ymlを更新してC89用リポジトリ各所に反映しますた。
