### ISSUE TITLE
行頭ではないコメントがシンタックスハイライトされる

### ISSUE THREAD

**Issue by Nkzn** [vvakame/language-review#50]
ReVIEWのコメント（`#@#`）は行頭しか効かない挙動になっているようです。（undocumented）

一方、language-reviewでは行末コメントもシンタックスハイライトしています。行頭以外にコメント記法を書いた場合は、ハイライトしない挙動のほうがいいのではないでしょうか。

### Editor

行末コメントがハイライトされます。

![2015-11-21 19 19 49](https://cloud.githubusercontent.com/assets/434227/11318030/a56859d2-9085-11e5-916d-84ea4d1d557e.png)

### Preview

![2015-11-21 19 19 58](https://cloud.githubusercontent.com/assets/434227/11318255/5b5e49a2-908d-11e5-87ea-670f4930e94e.png)

Ruby版のReVIEWでも同様の表示になったので、プレビューの挙動は正しそうです。

**Comment by vvakame** [comment]
ハイライトは正規表現を組み合わせて頑張って行う感じですごい辛いのだ… patches welcome! pull requestくれてもよいのよ…！
https://github.com/vvakame/language-review/blob/master/grammars/review.json これのどこかを直せば治る(確信

**Comment by vvakame** [comment]
PRもらって終わってたやつだった
