### ISSUE TITLE
<imgdir>/<id>.<ext>形式の画像でエラーが出る

### ISSUE THREAD

**Issue by kanzmrsw** [vvakame/language-review#53]
https://github.com/kmuto/review/wiki/ImagePath
にある定義では探索順序最下位に

`<imgdir>/<id>.<ext>`

があるけど，現状language-reviewではエラーが出るのを抑止したい。
![screenshot from 2016-03-16 14-31-29](https://cloud.githubusercontent.com/assets/388826/13802901/ca8a7840-eb83-11e5-8353-198cee8fe99d.png)

**Comment by vvakame** [comment]
そんな記法もあったのか(白目

**Comment by vvakame** [comment]
review.jsをリリースして→language-reviewをリリース したら治るとこまでやった。

**Comment by vvakame** [comment]
OKのはず

**Comment by kanzmrsw** [comment]
thx！
