### ISSUE TITLE
[0.12.6] プレビューペインをトグルで閉じられない

### ISSUE THREAD

**Issue by muojp** [vvakame/language-review#55]
## 現象

 `Cmd+Shift+I` の二度押しでプレビューペインが閉じない(以前のバージョンでは閉じていた)

## 再現手順

 * MacOSにてlanguage-review 0.12.6をインストールして.reファイルを開いた状態にする
 *  `Cmd+Shift+I` を叩き、プレビューを表示
 * その状態で再度 `Cmd+Shift+I` を叩く

## 期待される挙動

プレビューペインが閉じる

## 実際の挙動

反応がない(プレビューペインは表示されっぱなし)

related? https://github.com/vvakame/language-review/issues/54

**Comment by vvakame** [comment]
今試したら再現しなかった…

**Comment by vvakame** [comment]
Atom 1.7.3+language 0.13.0で再現しなくなってた…
