### ISSUE TITLE
[0.12.6] 文書のアウトラインが開かない

### ISSUE THREAD

**Issue by muojp** [vvakame/language-review#56]
## 現象

 `Cmd+Shift+O` を押してもアウトラインが表示されない(Packages > Re:VIEWのメニューを辿っても同様)

## 再現手順

 * MacOSにてlanguage-review 0.12.6をインストールして.reファイルを開いた状態にする
 *  `Cmd+Shift+O` を叩く、またはPackages > Re:VIEWのメニューを辿ってToggle Outlineを実行する

## 期待される挙動

文書のアウトラインが表示される

## 実際の挙動

反応がない

related? #54, #55

**Comment by vvakame** [comment]
これも今のところ再現しない

**Comment by vvakame** [comment]
Atom 1.7.3+language 0.13.0で再現しなくなってた…

**Comment by muojp** [comment]
いつのまにか手元もいけるようになってた。なんだったんだろう

**Comment by vvakame** [comment]
AtomのVersionでは感あるけどrelease noteみてもそれっぽい修正がないのよね…
